set nocompatible
filetype off

"Setting up Vundle - the vim plugin bundler
let iCanHazVundle=1
let vundle_readme=expand('~/.vim/bundle/vundle/README.md')
if !filereadable(vundle_readme)
    echo "Installing Vundle.."
    echo ""
    silent !mkdir -p ~/.vim/bundle
    silent !git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
    let iCanHazVundle=0
endif
set rtp+=~/.vim/bundle/vundle/
set rtp+=$GOROOT/misc/vim

call vundle#rc()
Bundle 'gmarik/vundle'

"Bundle 'altercation/vim-colors-solarized' "T-H-E colorscheme
Bundle 'Valloric/YouCompleteMe'
Bundle "pangloss/vim-javascript"
Bundle 'adimit/prolog.vim'
Bundle 'xolox/vim-misc'
Bundle 'xolox/vim-session'
Bundle 'tsaleh/vim-matchit'
Bundle 'tpope/vim-fugitive'
"Bundle 'myusuf3/numbers.vim'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'scrooloose/syntastic'
Bundle 'tpope/vim-surround'
Bundle 'MarcWeber/vim-addon-mw-utils'
Bundle 'tomtom/tlib_vim'
Bundle 'honza/snipmate-snippets'
Bundle 'garbas/vim-snipmate'
Bundle 'c9s/bufexplorer'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/nerdcommenter'
Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
Bundle 'tpope/vim-rails.git'
Bundle 'vexxor/phpdoc.vim'
Bundle 'kien/ctrlp.vim'
Bundle 'Lokaltog/vim-powerline'
"Bundle 'vim-ruby/vim-ruby'
"Bundle 'ervandew/supertab'
Bundle 't9md/vim-ruby-xmpfilter'
Bundle 'sjl/gundo.vim'
Bundle 'rking/ag.vim'

" vim-scripts repos
"Bundle 'PIV'
"Bundle 'Command-T'
"Bundle 'FuzzyFinder'
"Bundle 'HTML-AutoCloseTag'
Bundle 'VimCalc'
Bundle 'phpcomplete.vim'
Bundle 'xml.vim'
Bundle 'camelcasemotion'
Bundle 'L9'
Bundle 'preview'
Bundle 'taglist.vim'

if iCanHazVundle == 0
    echo "Installing Bundles, please ignore key map error messages"
    echo ""
    :BundleInstall
endif
" non github repos
"Bundle 'git://git.wincent.com/command-t.git'

filetype plugin indent on     " required!
"let g:Powerline_symbols = 'fancy'
"source ~/.vim/bundle/powerline/build/lib/powerline/ext/vim/source_plugin.vim
"python from powerline.ext.vim import source_plugin; source_plugin()
"
" Brief help
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install(update) bundles
" :BundleSearch(!) foo - search(or refresh cache first) for foo
" :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle command are not allowed..
syntax on
set pastetoggle=<F3>
set ssop-=options
set encoding=utf-8
set history=512
set undolevels=512
set colorcolumn=80
set laststatus=2
set visualbell
set noerrorbells
set wrapscan
set noswapfile
"set nobackup
set backup
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set backupskip=/tmp/*,/private/tmp/*
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set writebackup
set autoindent
set copyindent
set showmatch
set ruler
set hlsearch
set wildmenu
set incsearch
set number
set tabstop=4
set shiftwidth=4
set softtabstop=4
set ignorecase
set smartcase
set smarttab
set lazyredraw
set expandtab
set modelines=0
set backspace=start,indent,eol
set t_Co=256

set list
set listchars=tab:>.,trail:.,extends:#,nbsp:.

"let mapleader=","       " leader is comma
" allows cursor change in tmux mode
if exists('$TMUX')
    let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
    let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
    let &t_SI = "\<Esc>]50;CursorShape=1\x7"
    let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

let g:solarized_termcolors=256
set background=dark
colorscheme solarized

" CtrlP settings
let g:ctrlp_user_command = 'ag %s -l --nocolor --hidden -g ""'

"let g:EasyMotion_leader_key = '<Leader>'

let g:DisableAutoPHPFolding=1
let Tlist_Ctags_Cmd='/usr/bin/ctags'
let b:match_ignorecase = 1

let g:session_autosave = 'no'

"Shortcuts
nmap <S-Tab> :TlistToggle<CR>
map <Bar> :NERDTreeToggle<CR>
"map <F4> :BufExplorerVerticalSplit<CR>
"vmap <F6> :fold<CR>
map <C-m> :set rnu<CR>
map <C-b> :set nu<CR>
map <C-c> :nohlsearch<CR>
"map <C-S-l> :set rl<CR>
"map <C-S-k> :set norl<CR>
map <C-l> :tabn<CR>
map <C-h> :tabp<CR>
map <C-n> :tabnew<CR>
"map <C-x> :tabclose<CR>
map <CR> :NumbersToggle<CR> 
map <leader>c :Calc<CR> 

"seeing is believing key bindings
let g:xmpfilter_cmd = "seeing_is_believing"
autocmd FileType ruby nmap <buffer> <F5> <Plug>(seeing_is_believing-run)
autocmd FileType ruby xmap <buffer> <F5> <Plug>(seeing_is_believing-run)
autocmd FileType ruby imap <buffer> <F5> <Plug>(seeing_is_believing-run)

cmap w!! %!sudo tee > /dev/null %

" change key bindings
nnoremap ; :
" move vertically by visual line
nnoremap j gj
nnoremap k gk
" move to beginning/end of line
nnoremap B ^
nnoremap E $
" $/^ doesn't do anything
"nnoremap $ <nop>
"nnoremap ^ <nop>
" highlight last inserted text
nnoremap gV `[v`]
nnoremap <leader>u :GundoToggle<CR>
" open ag.vim
nnoremap <leader>a :Ag

"autocmd FileType php set omnifunc=phpcomplete#CompletePHP
"autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html,xml set listchars-=tab:>.

au BufRead,BufNewFile *.php		set indentexpr= | set smartindent
".phps files handled like .php
au BufRead,BufNewFile *.phps		set filetype=php

"ruby configs
"autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete
autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1
autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1

"improve autocomplete menu color
highlight Pmenu ctermbg=gray ctermfg=black gui=bold

"Use filetype plugins, e.g. for PHP
"autocmd FileType php noremap <C-M> :w! <CR>:!/usr/bin/php %<CR>
inoremap <C-K> <ESC> :call PhpDocSingle()<CR>
nnoremap <C-K> :call PhpDocSingle()<CR>
vnoremap <C-K> :call PhpDocRange()<CR>
let g:pdv_cfg_Author = "Amin Saeedi, <amin.w3dev@gmail.com>"
"let g:pdv_cfg_Copyright = "2011 Hippo Project"
"let g:pdv_cfg_Package = "Hippo Server"
"let g:pdv_cfg_License = ""
let g:pdv_cfg_Version = "0.0.1"
